Handu/urls.py
from django.conf.urls import url, include
#from django.contrib import admin
from rest_framework import routers
from hd_demo import views
#router = routers.DefaultRouter()
#router.register(r'users', views.user_list)

urlpatterns = [
    url(r'^api/', include('hd_demo.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api-auth/login',views.LoginViewSet.as_view()),
    url(r'^hd_mesos/', include('hd_mesos.urls',namespace="hd_mesos")),
    url(r'^hd_ansible/', include('hd_ansible.urls',namespace="hd_ansible")),
    url(r'^hd_mysql/', include('hd_mysql.urls',namespace="hd_mysql")),
    url(r'^hd_common/', include('hd_common.urls',namespace="hd_common")),
]

hd_mesos/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class HostInfo(models.Model):
    hostname=models.CharField(max_length=32)
    ip=models.CharField(max_length=16,primary_key=True)
    software = models.CharField(max_length=128,default="")
    tags = models.CharField(max_length=64,default="")
    idle = models.BooleanField(default=True)
    vginfo = models.TextField(null=True)
    memory_total = models.IntegerField(default=0)
    memory_used = models.IntegerField(default=0)
    memory_free = models.IntegerField(default=0)

class Users(models.Model):
    username = models.CharField(max_length=32,primary_key=True)
    nickname = models.CharField(max_length=16)
    password = models.CharField(max_length=128)
    role = models.PositiveSmallIntegerField(default=1)
    

class HostGroup(models.Model):
    id = models.AutoField(primary_key=True)
    groupname = models.CharField(max_length=32,unique=True)
    
class Host_Group(models.Model):
    id = models.AutoField(primary_key=True)
    ip = models.ForeignKey(HostInfo)
    group = models.ForeignKey(HostGroup)
    
class User_Host(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.ForeignKey(Users)
    ip = models.ForeignKey(HostInfo)

class User_Hostgroup(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.ForeignKey(Users)
    group = models.ForeignKey(HostGroup)
    
class User_Task(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.ForeignKey(Users)
    taskid = models.CharField(max_length=48,default="")
    taskname = models.CharField(max_length=32,default="")
    acked = models.BooleanField(default=False)
    star_time=models.DateTimeField()
    hosts=models.CharField(max_length=128)
    status=models.CharField(max_length=50,default="Running")
    result=models.TextField(null=True)
    date_done=models.DateTimeField(null=True)
    

templates/mesos/custom/custom-layout.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="shortcut icon" href="/static/favicon.ico" type="image/x-icon">
<!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
<title>HanDu Automation Platforms</title>
<!-- Bootstrap -->
<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link href="/static/metisMenu/metisMenu.min.css" rel="stylesheet">
<link href="/static/font-awesome/css/font-awesome.min.css" rel="stylesheet">
{% block css%} {% endblock %}
<link rel="stylesheet" type="text/css" href="/static/css/handu.css">
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
      <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div id='wrapper'>
   <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
     <div class="navbar-header">
     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/hd_mesos/index.html">HanDu Admin</a>
       </div>
     <ul class="nav navbar-top-links navbar-right">
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false">
             <i class="fa fa-user fa-fw"></i> 
             <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
             <li><a data-toggle="modal" data-target="#userModal" id="userinfo"><i class="fa fa-user fa-fw"></i> 用户信息</a>
                        </li>
              <li><a href="#"><i class="fa fa-gear fa-fw"></i> 设置</a>
                        </li>
              <li class="divider"></li>
              <li><a href="/hd_mesos/logout"><i class="fa fa-sign-out fa-fw"></i> 退出</a>
                        </li>
         </ul>
      </li>
    </ul>
              <div>
      <p class="navbar-text navbar-right">{{request.session.is_login}}</p>
      </div>
     <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav in" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                                </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a href="/hd_mesos/index.html"><i class="fa fa-dashboard fa-fw"></i> 仪表盘</a>
                        </li>
                         <li>
                            <a href="#"><i class="fa fa-server fa-fw"></i> 服务器<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level collapse">
                                <li>
                                    <a href="/hd_mesos/hostlist.html">主机列表</a>
                                </li>
                                <li>
                                    <a href="/hd_mesos/hostgroups.html">主机组列表</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                      <li>
                            <a href="#"><i class="fa fa-retweet fa-fw"></i> Ansible<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level collapse">
                                <li>
                                    <a href="#">Tomcat<span class="fa arrow"></span></a>
                                    <ul class="nav nav-third-level collapse">
                                     <li>
                                       <a href="/hd_ansible/tomcat/projectdev">项目部署</a>
                                       <a href="/hd_ansible/tomcat/rollback">历史版本回滚</a>
                                     </li>
                                    </ul>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
   </nav>
   <div id="page-wrapper">
     	{% block content %}
		{% endblock %}
   </div>
                  <!-- 模态框（Modal） -->  
            <div class="modal fade" id="userModal" tabindex="-1" role="dialog">  
                <div class="modal-dialog">  
                    <div class="modal-content">  
                        <div class="modal-header">  
                            <button type="button" class="close" data-dismiss="modal">  
                  ×  
            </button>  
                        </div>
                   <form id="useredit" role="form" method="post" action="useredit" class="form-horizontal">
							{% csrf_token %}  
                        <div class="modal-body col-md-12 col-md-offset-1">
                        	<div class="form-group">
								<label for="username" class="col-md-2 control-label">用户名</label>
								 <div class="col-md-6">
								 <input class="form-control" name="Username" id="username" readonly="readonly"> </div>
						     </div>
						 <div class="form-group">
								<label for="nickname" class="col-md-2 control-label">昵称</label>
								 <div class="col-md-6">
								 <input class="form-control" name="Nickname" id="nickname" required data-msg-required="请输入昵称"> 
								 </div>
						 </div>
	                   <div class="form-group">
								<label for="password" class="col-md-2 control-label">密码</label>
								 <div class="col-md-6">
								 <input class="form-control" placeholder="Password" name="Password" id="password" type="password" rangelength="6,12"> 
								 </div>
						</div>
				        <div class="form-group">
								<label for="confirmpass" class="col-md-2 control-label">确认密码</label>
								 <div class="col-md-6">
								 <input class="form-control" placeholder="Confirm Password" name="Confirmpass" id="confirmpass" type="Password" equalTo="#password" data-msg-equalTo="两次密码不相同"> 
								 </div>
						</div>
						</div>
                        <div class="modal-footer">  
                            <button type="button" class="btn btn-default" data-dismiss="modal" id="dataclose">关闭  
            </button>  
                            <button type="submit" class="btn btn-primary" id="datasubmit">  
               保存
            </button>  
                        </div>
                   </form>
                    </div>  
                    <!-- /.modal-content -->  
                </div>  
       </div>
</div>


<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="//cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
<script src="/static/bootstrap/js/bootstrap.js"></script>
<script src="/static/metisMenu/metisMenu.min.js"></script>
<script src="/static/jquery-validate/jquery.validate.js"></script>
<script src="/static/jquery-validate/messages_zh.js"></script>
<!--<script src="https://unpkg.com/vue/dist/vue.js"></script> -->
<!-- Include all compiled plugins (below), or include individual files as needed -->
{% block js %} {% endblock %}
<script src="/static/js/handu.js"></script>
<script></script>
</body>
</html>

templates/mesos/custom/hostgroups.html
{% extends "mesos/custom/custom-layout.html" %}
{% block css%}
<!-- <link href="/static/datatables/css/jquery.dataTables.css" rel="stylesheet"> -->
<link href="/static/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet">
<link href="/static/datatables-responsive/dataTables.responsive.css" rel="stylesheet">
{% endblock %}
{% block content %}
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">主机组列表</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                       
                            <table width="100%" class="table table-striped table-bordered table-hover" id="group-info">
                                <thead>
                                    <tr>
                                        <th>序号</th>
                                        <th>主机组名</th>
                                        <th>主机IP</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for group in groups%}
                                    <tr>
                                        <td></td>
                                        <td>{{group.groupname}}</td>
                                        <td>
                                        {% for host in group.host_group_set.all %}
                                         {% if group.id == host.group.id %}
                                         {{host.ip.ip}}
                                         {% endif %}
                                         {% endfor %}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
{% endblock %}
{% block js%}
<script src="/static/datatables/js/jquery.dataTables.min.js"></script>
<script src="/static/datatables-plugins/dataTables.bootstrap.min.js"></script>
<script src="/static/datatables-responsive/dataTables.responsive.js"></script>
<script>
    $(document).ready(function() {
        var table = $('#group-info').DataTable({
            "responsive": true,
            "lengthChange": false,
            "oLanguage": {//国际语言转化
            "oAria": {
                "sSortAscending": " - click/return to sort ascending",
                "sSortDescending": " - click/return to sort descending"
            }, 
            "sLengthMenu": "显示 _MENU_ 记录",
            "sZeroRecords": "对不起，查询不到任何相关数据",
            "sEmptyTable": "未有相关数据",
            "sLoadingRecords": "正在加载数据-请等待...",
            "sInfo": "当前显示 _START_ 到 _END_ 条，共 _TOTAL_ 条记录。",
            "sInfoEmpty": "当前显示0到0条，共0条记录",
            "sInfoFiltered": "（数据库中共为 _MAX_ 条记录）",
            "sProcessing": "<img src='../resources/user_share/row_details/select2-spinner.gif'/> 正在加载数据...",
            "sSearch": "模糊查询：",
            "sUrl": "",
            //多语言配置文件，可将oLanguage的设置放在一个txt文件中，例：Javascript/datatable/dtCH.txt
            "oPaginate": {
                "sFirst": "首页",
                "sPrevious": " 上一页 ",
                "sNext": " 下一页 ",
                "sLast": " 尾页 "
                }            
           },
      });
      table.on( 'order.dt search.dt', function () {
          table.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
              cell.innerHTML = i+1;
          } );
      } ).draw();
    });
</script>
{% endblock %}

templates/mesos/custom/hostlist.html
{% extends "mesos/custom/custom-layout.html" %}
{% block css%}
<!-- <link href="/static/datatables/css/jquery.dataTables.css" rel="stylesheet"> -->
<link href="/static/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet">
<link href="/static/datatables-responsive/dataTables.responsive.css" rel="stylesheet">
{% endblock %}
{% block content %}
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">主机列表</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                       
                            <table width="100%" class="table table-striped table-bordered table-hover" id="host-info">
                                <thead>
                                    <tr>
                                        <th>序号</th>
                                        <th>主机名</th>
                                        <th>IP地址</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for host in hosts%}
                                    <tr>
                                        <td></td>
                                        <td>{{host.hostname}}</td>
                                        <td>{{host.ip}}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
{% endblock %}
{% block js%}
<script src="/static/datatables/js/jquery.dataTables.min.js"></script>
<script src="/static/datatables-plugins/dataTables.bootstrap.min.js"></script>
<script src="/static/datatables-responsive/dataTables.responsive.js"></script>
<script>
    $(document).ready(function() {
        var table = $('#host-info').DataTable({
            "responsive": true,
            "lengthChange": false,
            "bAutoWidth": false,
            "oLanguage": {//国际语言转化
            "oAria": {
                "sSortAscending": " - click/return to sort ascending",
                "sSortDescending": " - click/return to sort descending"
            }, 
            "sLengthMenu": "显示 _MENU_ 记录",
            "sZeroRecords": "对不起，查询不到任何相关数据",
            "sEmptyTable": "未有相关数据",
            "sLoadingRecords": "正在加载数据-请等待...",
            "sInfo": "当前显示 _START_ 到 _END_ 条，共 _TOTAL_ 条记录。",
            "sInfoEmpty": "当前显示0到0条，共0条记录",
            "sInfoFiltered": "（数据库中共为 _MAX_ 条记录）",
            "sProcessing": "<img src='../resources/user_share/row_details/select2-spinner.gif'/> 正在加载数据...",
            "sSearch": "模糊查询：",
            "sUrl": "",
            //多语言配置文件，可将oLanguage的设置放在一个txt文件中，例：Javascript/datatable/dtCH.txt
            "oPaginate": {
                "sFirst": "首页",
                "sPrevious": " 上一页 ",
                "sNext": " 下一页 ",
                "sLast": " 尾页 "
                }            
           },
			  "aoColumns": [//设定各列宽度   
			            {"sWidth": "40px"}, 
			            {"sWidth": "100px"},
			            {"sWidth": "100px"},
			            ]  
      });
      table.on( 'order.dt search.dt', function () {
          table.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
              cell.innerHTML = i+1;
          } );
      } ).draw();
    });
</script>
{% endblock %}

templates/mesos/custom/index.html
{% extends "mesos/custom/custom-layout.html" %}
{% block css%}
{% endblock %}
{% block content %}
{% endblock %}
{% block js%}
{% endblock %}